-- 시퀀스 삭제
DROP SEQUENCE academyEduSeq;
DROP SEQUENCE academySeq;
DROP SEQUENCE adlistSeq;
DROP SEQUENCE adminInfoId;
DROP SEQUENCE agencySeq;
DROP SEQUENCE answerSeq;
DROP SEQUENCE blockUserSeq;
DROP SEQUENCE boardLikeSeq;
DROP SEQUENCE boardSeq;
DROP SEQUENCE bookLikeSeq;
DROP SEQUENCE bookprcByUserSeq;
DROP SEQUENCE bookSeq;
DROP SEQUENCE commentSeq;
DROP SEQUENCE crtByBookSeq;
DROP SEQUENCE crtByJobSeq;
DROP SEQUENCE crtLikeSeq;
DROP SEQUENCE crtSchSeq;
DROP SEQUENCE crtSeq;
DROP SEQUENCE crtTestSeq;
DROP SEQUENCE crtTestTypeSeq;
DROP SEQUENCE crtTypeSeq;
DROP SEQUENCE departByJobSeq;
DROP SEQUENCE departSeq;
DROP SEQUENCE domainSeq;
DROP SEQUENCE faqSeq;
DROP SEQUENCE forbiddenSeq;
DROP SEQUENCE indexSeq;
DROP SEQUENCE jobgroupSeq;
DROP SEQUENCE jobSeq;
DROP SEQUENCE noticeBoardSeq;
DROP SEQUENCE pointSeq;
DROP SEQUENCE profileSeq;
DROP SEQUENCE qnaSeq;
DROP SEQUENCE reportBoardSeq;
DROP SEQUENCE reportCommentSeq;
DROP SEQUENCE reportCtgSeq;
DROP SEQUENCE studyJoinSeq;
DROP SEQUENCE studyMemberSeq;
DROP SEQUENCE studySeq;
DROP SEQUENCE myCrtSeq;
DROP SEQUENCE crtFaqSeq;
DROP SEQUENCE crtPassRateSeq;
DROP SEQUENCE crtboardSeq;
DROP SEQUENCE crtcommentSeq;
DROP SEQUENCE toDoListSeq;
DROP SEQUENCE pointHistorySeq;


-- 테이블 삭제
Drop table tblCrtComment;
Drop table tblCrtBoard;
Drop table tblCrtFaq ;
Drop table tblCrtPassRate ;

Drop table tblDomain ;
Drop table tblPointHistory ;
Drop table tblPoint ;
Drop table tblProfile ;
Drop table tblBookLike  ;
Drop table tblCrtLike  ;
Drop table tblBoardLike ;
Drop table tblReportComment ;
Drop table tblReportBoard ;
Drop table tblReportCtg ;
Drop table tblComment ;
Drop table tblBoard ;
Drop table tblStudyMember ;
Drop table tblStudy;
Drop table tblStudyJoin ;
Drop table tblAnswer ;
Drop table tblQna ;
Drop table tblBookprgByUser ;
Drop table tblBlockUser ;

Drop table tblAdList ;
Drop table tblForbidden ;
Drop table tblNoticeBoard ;
Drop table tblMyCrt;
Drop table tblAdminInfo ;
Drop table tblFaq ;
Drop table tblAcademyEdu ;
Drop table tblAcademy ;
Drop table tblCrtByBook ;
Drop table tblIndex ;
Drop table tblBook ;
Drop table tblDepartByJob ;
Drop table tblDepart ;
Drop table tblCrtByJob ;
Drop table tblJob  ;
Drop table tblJobgroup ;
Drop table tblCrtSch  ;
Drop table tblcrtTest ;
Drop table tblCrtTestType ;
Drop table tblCrt ;
Drop table tblAgency ;
Drop table tblCrtType;
Drop table tblUserInfo ;
Drop table tblToDoList;

